using System;
using System.Text;
using System.Threading.Tasks;
using VerifyTests;
using VerifyXunit;
using Xunit;

namespace DataFac.Template.Tests
{
    public class SampleVerifyTests
    {
        [Fact]
        public async Task CheckVerifySetup()
        {
            await VerifyChecks.Run();
        }

        [Fact]
        public async Task VerifyGeneratedText()
        {
            VerifyTestHelpers.EnsureInitialized();

            StringBuilder builder = new StringBuilder();
            builder.AppendLine("// <auto-generated>");
            builder.AppendLine("// Hello, World!");
            builder.AppendLine("// </auto-generated>");
            string text = builder.ToString();
            await Verifier.Verify(text);
        }
    }
}